#!/bin/bash

./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01
./my-ls
sleep 0.01

